#!/bin/bash

cd /home/matt
/usr/bin/rrdtool graph /dev/shm/past-1h.png -s now-1h -e now -t "Past Hour" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
/usr/bin/rrdtool graph /dev/shm/past-3h.png -s now-3h -e now -t "Past 3 Hours" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
/usr/bin/rrdtool graph /dev/shm/past-1d.png -s now-1d -e now -t "Past Day" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
/usr/bin/rrdtool graph /dev/shm/past-1w.png -s now-1w -e now -t "Past Week" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
/usr/bin/rrdtool graph /dev/shm/past-30d.png -s now-30d -e now -t "Past Month" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
/usr/bin/rrdtool graph /dev/shm/past-1y.png -s now-1y -e now -t "Past Year" -v "Temperature (C)" -w 800 -h 600 DEF:temp=heater.rrd:temp:AVERAGE DEF:setpoint=heater.rrd:setpoint:AVERAGE DEF:heat=heater.rrd:heat:AVERAGE 'CDEF:heatscaled=heat,5,*' LINE:temp#0000ff:"Temperature" LINE2:setpoint#00aa00:"Setpoint" LINE:heatscaled#ff0000:"Heat"
